# Introduction

We will solve exercises together using SQL and Python. We will use the chinook database. Please check the database ERD model below:

![img](https://www.sqlitetutorial.net/wp-content/uploads/2015/11/sqlite-sample-database-color.jpg)

# Questions

1) Create a method `bark` for class `Dog`, which prints out `Woof!`. The amount of 'woofs' depends on the dog size.
Example:

Object of class `Dog` has a parameter size set to 5. <br>
the outcome of `woof` method would be: <br>
Woof! Woof! Woof! Woof! Woof!

2) Create a class `Puppy` which inherits from the `Dog` class. It should inherit the Constructor class and overload a `woof` method.

3) extract all invoices from the database with SQL and Python

4) calculate sales by customer id using SQL and Python

5) find top 10 biggest customers by sales value using pandas dataframe